In [1]:
import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score

from sklearn.compose import ColumnTransformer

In [2]:
df=pd.read_csv('train (1).csv',usecols=['Age','Fare','SibSp','Parch','Survived'])

In [3]:
df.dropna(inplace=True)

In [5]:
df.head()

   Survived   Age  SibSp  Parch     Fare
0         0  22.0      1      0   7.2500
1         1  38.0      1      0  71.2833
2         1  26.0      0      0   7.9250
3         1  35.0      1      0  53.1000
4         0  35.0      0      0   8.0500

In [6]:
df['Family']=df['SibSp']+df['Parch']

In [7]:
df.head()

   Survived   Age  SibSp  Parch     Fare  Family
0         0  22.0      1      0   7.2500       1
1         1  38.0      1      0  71.2833       1
2         1  26.0      0      0   7.9250       0
3         1  35.0      1      0  53.1000       1
4         0  35.0      0      0   8.0500       0

In [8]:
df.drop(columns=['SibSp','Parch'],inplace=True)

In [10]:
df.head()

   Survived   Age     Fare  Family
0         0  22.0   7.2500       1
1         1  38.0  71.2833       1
2         1  26.0   7.9250       0
3         1  35.0  53.1000       1
4         0  35.0   8.0500       0

In [11]:
X=df.drop(columns=['Survived'])
y=df['Survived']

In [12]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [13]:
X_train.head()

      Age     Fare  Family
328  31.0  20.5250       2
73   26.0  14.4542       1
253  30.0  16.1000       1
719  33.0   7.7750       0
666  25.0  13.0000       0

In [14]:
# Without Binarization
clf=DecisionTreeClassifier()
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)

In [15]:
accuracy_score(y_test,y_pred)

0.6293706293706294

In [16]:
np.mean(cross_val_score(DecisionTreeClassifier(),X,y,cv=10,scoring='accuracy'))

np.float64(0.6443270735524257)

In [17]:
# Applying Binarization

from sklearn.preprocessing import Binarizer

In [18]:
trf = ColumnTransformer([
    ('bin',Binarizer(copy=False),['family'])
],remainder='passthrough')

In [19]:
X_train_trf=trf.fit_transform(X_train)
X_test_trf=trf.transform(X_test)

ValueError: A given column is not a column of the dataframe